# Build Settings
markdown: kramdown
kramdown:
  input: GFM

timezone: America/New_York

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

paginate: 5

future: false

# Template Settings
baseurl: ""

# SEO Settings
url: "https://dkrichards.com"
title: Keith Richards
description: >-
  I am a dad in perpetual training, a curious software engineer, a Marine Corps veteran, and a consummate bro.

logo: /assets/favicon.png

author:
  linkedin: dkrichards86
  github: dkrichards86

social:
  name: Keith Richards
  links:
    - https://github.com/dkrichards86
    - https://www.linkedin.com/in/dkrichards/

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/dkrichards_square.jpg
