# Build Settings
markdown: kramdown
kramdown:
  input: GFM

timezone: America/New_York

future: false

plugins:
  - jekyll-archives
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-target-blank
  - jekyll-titles-from-headings

paginate: 8

exclude:
  - claude.md

# Template Settings
baseurl: ""

# SEO Settings
url: "https://dkrichards.com"
title: Keith Richards
description: >-
  I am a dad in perpetual training, a curious software engineer, a Marine Corps veteran, and a consummate bro.

logo: /assets/favicon.png

author:
  linkedin: dkrichards86
  github: dkrichards86

social:
  name: Keith Richards
  links:
    - https://github.com/dkrichards86
    - https://www.linkedin.com/in/dkrichards/

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/dkrichards_square.jpg

jekyll-archives:
  enabled:
    - year
    - tags
  layouts:
    year: year-archive
    tag: tag-archive
  permalinks:
    year: '/archives/year/:year/'
    tag: '/archives/tag/:name/'